# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('quantity', models.IntegerField(default=10)),
                ('cat_price', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackID', models.IntegerField()),
                ('source_address', models.CharField(max_length=300)),
                ('destination_address', models.CharField(max_length=300)),
                ('sending_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('price', models.FloatField(default=1.0)),
                ('isReceived', models.BooleanField(default=False)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CorporateUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
                ('telephone', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('discount_factor', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackID', models.IntegerField()),
                ('source_address', models.CharField(max_length=300)),
                ('destination_address', models.CharField(max_length=300)),
                ('sending_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('isReceived', models.BooleanField(default=False)),
                ('price', models.FloatField(default=7.0)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.Category')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.AddField(
            model_name='corporateshipment',
            name='corparateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.CorporateUser'),
        ),
    ]
