# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateshipment',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='corporateshipment',
            name='trackID',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='trackID',
            field=models.CharField(max_length=12),
        ),
    ]
