# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0002_auto_20170510_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='categoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_app.Category'),
        ),
    ]
