# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0003_auto_20170524_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateshipment',
            name='customer_name',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='corporateshipment',
            name='customer_surname',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='userID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
