# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0004_auto_20170525_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporateshipment',
            old_name='corparateID',
            new_name='corporateID',
        ),
    ]
