# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0005_auto_20170525_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateshipment',
            name='price',
        ),
    ]
