name: Example Print Message Workflow

on:
  push:

jobs:
  print_message:
    name: test-pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "Hello, GitHub Actions!"